# Build settings
permalink   : /blog/:year/:title/
markdown    : redcarpet
highlighter : pygments

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Shane Li
description: "Shane's personal webpage"
keywords: "Shane, Li"
url: www.potatoshane.github.io
baseurl: "/potatoshane.io"
# baseurl: ""

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# google_analytics:
repo: http://github.com/potatoshane/potatoshane.io
disqus_shortname: "shane"

# Author settings
author:
  name      : Shane Li
  job       : Student
  bio       : "Purdue University Computer Science Class of 2019."
  thumb     : /images/author.jpg
  email     : li2137@purdue.edu
  url       : http://shaneli.me
  github    : http://github.com/potatoshane
  #twitter   : http://twitter.com/potatoshane
  facebook  : https://www.facebook.com/shane.li.37
  linkedin  : http://linkedin.com/in/shanelipurdue

# navbar pages
navbar:
  #- slug: about
  #  title: About
   - slug: resume
     title: Resume
  # - slug: skills
  #   title: Skills
  #- slug: blog
  #  title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]